source 'https://rubygems.org'

gem 'colorator'   , '0.1'
gem 'fileutils'   , '0.7'
gem 'highline'    , '1.6.19'
gem 'jekyll'      , '1.2.1'
gem 'liquid'      , '2.5.3'
gem 'pygments.rb' , '0.5.2'
gem 'rake'        , '10.1.0'
gem 'rdiscount'   , '2.1.6'
gem 'stringex'    , '2.0.8'
gem 'sweetie'     , '1.0.1'
gem 'ri_cal'      , '0.8.8'
gem 'tzinfo'      , '1.0.1'
gem 'nokogiri'    , '1.6.0'
