source 'https://rubygems.org'

gem "middleman", "~> 3.3.12"
gem "middleman-livereload", "~> 3.1.0"
gem 'middleman-search_engine_sitemap', '~> 1.1'
gem 'middleman-disqus', '~> 1.0'
gem 'middleman-syntax', '~> 1.2'
gem 'middleman-piwik'
gem 'font-awesome-middleman'


gem "middleman-blog"
gem "nokogiri"

gem 'redcarpet'

gem "builder" # used for feed.xml
gem "wdm", "~> 0.1.0", :platforms => [:mswin, :mingw] # For faster file watcher updates on Windows:
gem "tzinfo-data",     :platforms => [:mswin, :mingw] # Windows does not come with time zone data

